# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84bac58d3e03766e59fa572755b6b3102bd28ae807ccf462c9e6b2be2d8b2461879d7a1cbacc47075c80520e5bf8063e31cdada0299c88c715d25789c88319b8

test:
  secret_key_base: 161d7cd052808d6d9a53024bea3880524966432613442b2c62faf256e8d3128b5d3aef54ca91d2f4f00141f82385f5b39c582605100ee84b9cd49520768bd943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
